spring.application.name=uberApp

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Vinay123
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#security config
jwt.secretKey=gghauhfashdklHEOYQ87Y598Q34TU98PWERHGP98WU9P87W93P4U09QJEFOIAWEHIHFoicapw984u598pq34ut

#smtp config
spring.mail.username=abhishaw5339@gmail.com
spring.mail.password=${SMTP_EMAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql